# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Class-Server-PreFork
version:      0.01-beta
version_from: lib/POE/Class/Server/PreFork.pm
installdirs:  site
requires:
    POE:                           0.27

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
